In [1]:
import pandas as pd
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter

e = 1.6e-19
m = 9.1e-31

In [22]:
data = pd.read_excel('C:/Users/Administrator/Dropbox/PRL/Python_Projects/IV_characteristic/Drift_Velocity.xlsx')
data

,B,n,n_Baseline,n_Low,n_High,T,T_Baseline,T_Low,T_High,Vp,V_Baseline,V_Low,V_High
0,31.80456,-12,198588000000000000,137886000000000000,408030000000000000,-12,9.14,8.08,11.20,-12,3.57,4.79,1.97
1,42.40607,-10,295470000000000000,171855000000000000,665310000000000000,-10,9.44,8.82,11.20,-10,3.17,4.91,1.81
2,53.00758,-8,379890000000000000,215070000000000000,910530000000000000,-8,9.79,9.07,10.80,-8,3.16,5.05,1.93
3,63.60910,-6,472350000000000000,253260000000000000,1059270000000000000,-6,9.78,9.28,10.90,-6,3.30,5.20,2.03
4,74.21061,-4,540690000000000000,285420000000000000,1111530000000000000,-4,10.30,9.33,11.00,-4,3.61,5.37,2.20
5,84.81213,-2,572850000000000000,305520000000000000,1121580000000000000,-2,10.60,9.12,11.00,-2,3.90,5.53,2.35
6,95.41365,0,576870000000000000,315570000000000000,1095450000000000000,0,10.60,8.73,10.60,0,4.04,5.59,2.47
7,106.01516,2,605010000000000000,329640000000000000,1037160000000000000,2,9.98,8.37,10.30,2,4.14,5.66,2.51
8,116.61668,4,586920000000000000,339690000000000000,938670000000000000,4,9.49,7.99,9.82,4,4.19,5.67,2.58
9,127.21819,6,556770000000000000,351750000000000000,777870000000000000,6,9.02,7.35,9.72,6,4.27,5.67,2.67
10,137.81971,8,520590000000000000,339690000000000000,596970000000000000,8,8.25,6.54,9.64,8,4.37,5.63,2.66
11,148.42123,10,452250000000000000,307530000000000000,480390000000000000,10,6.98,5.60,8.47,10,4.44,5.65,2.96
12,159.02274,12,373860000000000000,285420000000000000,448230000000000000,12,5.48,4.19,5.39,12,4.62,6.05,3.44
13,NaN,14,295470000000000000,273360000000000000,355770000000000000,14,3.78,3.17,3.24,14,4.74,6.17,3.92
14,NaN,16,245220000000000000,253260000000000000,309540000000000000,16,2.88,2.62,2.35,16,4.71,6.16,4.25
15,NaN,18,219090000000000000,227130000000000000,311550000000000000,18,2.51,2.29,2.06,18,4.61,6.02,4.43
16,NaN,20,184719000000000000,188739000000000000,285420000000000000,20,2.27,2.11,1.96,20,4.48,5.84,4.37
17,NaN,23,119796000000000000,121203000000000000,209040000000000000,23,2.24,1.77,1.61,23,3.92,5.23,4.06

In [35]:
position = np.array(data['n'])
B_list = np.array(data['B'])[0:-5]
n_base = np.array(data['n_Baseline'])
n_low = np.array(data['n_Low '])
n_high = np.array(data['n_High'])
T_base = np.array(data['T_Baseline'])
T_low = np.array(data['T_Low '])
T_high = np.array(data['T_High'])
V_base = np.array(data['V_Baseline'])
V_low = np.array(data['V_Low '])
V_high = np.array(data['V_High'])
print(B_list)

[ 31.80456  42.40607  53.00758  63.6091   74.21061  84.81213  95.41365
 106.01516 116.61668 127.21819 137.81971 148.42123 159.02274]